# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1baQgvh-dNr-F4FAKmUBVbIId0O4n9qk5
"""

from google.colab import files
uploaded = files.upload()

!unzip "archive 2.zip"

!mv "archive 2.zip" water_dataset.zip

!unzip water_dataset.zip

!ls

!ls train

!ls train/images | head

import tensorflow as tf

dataset = tf.keras.preprocessing.image_dataset_from_directory(
    "train",
    image_size=(224,224),
    batch_size=32
)

class_names = dataset.class_names
print("Classes:", class_names)

from tensorflow.keras import layers
from tensorflow.keras import models

model = models.Sequential([
    layers.Rescaling(1./255, input_shape=(224,224,3)),

    layers.Conv2D(32,(3,3),activation='relu'),
    layers.MaxPooling2D(),

    layers.Conv2D(64,(3,3),activation='relu'),
    layers.MaxPooling2D(),

    layers.Conv2D(128,(3,3),activation='relu'),
    layers.MaxPooling2D(),

    layers.Flatten(),
    layers.Dense(128,activation='relu'),
    layers.Dense(len(class_names),activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

model.fit(dataset, epochs=10)

model.save("water_leak_model.keras")

from google.colab import files
files.download("water_leak_model.keras")

from google.colab import files
uploaded = files.upload()

import numpy as np
from tensorflow.keras.preprocessing import image

img = image.load_img("IMG_4987.jpeg", target_size=(224,224))
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)

img = image.load_img("IMG_4987.jpeg", target_size=(224,224))

import tensorflow as tf

model = tf.keras.models.load_model("water_leak_model.keras")

prediction = model.predict(img_array)

print(prediction)

from PIL import Image
import numpy as np


img = Image.open("IMG_4987.jpeg")


img = img.resize((224,224))


img = np.array(img)


img = img / 255.0


img = np.expand_dims(img, axis=0)


pred = model.predict(img)

print(pred)

if pred[0][0] > 0.5:
    print("Water Leakage Detected 💧")
else:
    print("No Water Leakage")