# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X_xhgbKlp76SQ-6THdFqYZKNtt0N0hFn
"""

from google.colab import files
uploaded = files.upload()

!unzip 6ulxurymcmag1a8tnbmroq.zip

!ls

!ls images.cv_6ulxurymcmag1a8tnbmroq

!ls images.cv_6ulxurymcmag1a8tnbmroq/data

!ls images.cv_6ulxurymcmag1a8tnbmroq/data/train

!ls images.cv_6ulxurymcmag1a8tnbmroq/data/train | head

!ls "images.cv_6ulxurymcmag1a8tnbmroq/data/train/pothole road crevasse crack" | head

import os
import matplotlib.pyplot as plt
from PIL import Image

folder = "images.cv_6ulxurymcmag1a8tnbmroq/data/train/pothole road crevasse crack"

images = os.listdir(folder)[:5]

plt.figure(figsize=(10,5))

for i, img_name in enumerate(images):
    img_path = os.path.join(folder, img_name)
    img = Image.open(img_path)

    plt.subplot(1,5,i+1)
    plt.imshow(img)
    plt.axis("off")

plt.show()

import os

train_path = "images.cv_6ulxurymcmag1a8tnbmroq/data/train"

for folder in os.listdir(train_path):
    print(folder)

import tensorflow as tf

dataset = tf.keras.preprocessing.image_dataset_from_directory(
    "images.cv_6ulxurymcmag1a8tnbmroq/data/train",
    image_size=(224, 224),
    batch_size=32
)

class_names = dataset.class_names
print("Classes:", class_names)

from tensorflow.keras import layers
from tensorflow.keras import models

model = models.Sequential([
    layers.Rescaling(1./255, input_shape=(224,224,3)),

    layers.Conv2D(32, (3,3), activation='relu'),
    layers.MaxPooling2D(),

    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D(),

    layers.Conv2D(128, (3,3), activation='relu'),
    layers.MaxPooling2D(),

    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dense(len(class_names), activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

history = model.fit(
    dataset,
    epochs=10
)

from google.colab import files
uploaded = files.upload()

import numpy as np
from tensorflow.keras.preprocessing import image

img_path = list(uploaded.keys())[0]

img = image.load_img(img_path, target_size=(224,224))
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)

prediction = model.predict(img_array)
predicted_class = class_names[np.argmax(prediction)]

print("Prediction:", predicted_class)

if predicted_class in class_names:
    print("Road Issue Detected (Pothole)")
else:
    print("No Pothole")

model.save("pothole_model.h5")

model.save("pothole_model.keras")

from google.colab import files
files.download("pothole_model.keras")